builds:
  - main: ./cmd/kube-external-sync/main.go
    id: kube-external-sync
    binary: kube-external-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/alehechka/kube-external-sync.Version={{.Version}}
archives:
  - name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    format: binary
    replacements:
      amd64: x86_64
dist: _output
