//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/alehechka/kube-external-sync/api/types"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSyncRule) DeepCopyInto(out *ExternalSyncRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSyncRule.
func (in *ExternalSyncRule) DeepCopy() *ExternalSyncRule {
	if in == nil {
		return nil
	}
	out := new(ExternalSyncRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalSyncRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSyncRuleList) DeepCopyInto(out *ExternalSyncRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalSyncRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSyncRuleList.
func (in *ExternalSyncRuleList) DeepCopy() *ExternalSyncRuleList {
	if in == nil {
		return nil
	}
	out := new(ExternalSyncRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalSyncRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSyncRuleSpec) DeepCopyInto(out *ExternalSyncRuleSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(Ingress)
		**out = **in
	}
	in.Rules.DeepCopyInto(&out.Rules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSyncRuleSpec.
func (in *ExternalSyncRuleSpec) DeepCopy() *ExternalSyncRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalSyncRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRules) DeepCopyInto(out *NamespaceRules) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeRegex != nil {
		in, out := &in.ExcludeRegex, &out.ExcludeRegex
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.IncludeRegex != nil {
		in, out := &in.IncludeRegex, &out.IncludeRegex
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.IncludeAnnotation != nil {
		in, out := &in.IncludeAnnotation, &out.IncludeAnnotation
		*out = make(types.Annotations, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRules.
func (in *NamespaceRules) DeepCopy() *NamespaceRules {
	if in == nil {
		return nil
	}
	out := new(NamespaceRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rules) DeepCopyInto(out *Rules) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rules.
func (in *Rules) DeepCopy() *Rules {
	if in == nil {
		return nil
	}
	out := new(Rules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}
