apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsyncrules.kube-external-sync.io
  labels: {{- include "kube-external-sync.labels" . | nindent 4 }}
spec:
  group: kube-external-sync.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: 
                - namespace
              properties:
                namespace:
                  type: string
                service:
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                      default: Service
                      enum: 
                        - Service
                        # - Traefik Service
                    externalNameSuffix:
                      type: string
                      default: 'svc.cluster.local'
                      enum:
                        - 'svc.cluster.local'
                        - 'traefik.mesh'
                  required:
                    - name
                ingress:
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                      default: Ingress
                      enum: 
                        - Ingress
                        # - Ingress Route
                        # - Ingress Route TCP
                        # - Ingress Route UDP
                    topLevelDomain:
                      type: string
                    secretName: 
                      type: string
                  required:
                    - name
                    - topLevelDomain
                rules:
                  type: object
                  properties:
                    namespaces:
                      type: object
                      properties:
                        exclude:
                          type: array
                          items:
                            type: string
                        excludeRegex:
                          type: array
                          items:
                            type: string
                        include:
                          type: array
                          items:
                            type: string
                        includeRegex:
                          type: array
                          items:
                            type: string
                        includeAnnotation:
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                              value:
                                type: string
                              isRegex:
                                type: boolean
  scope: Cluster
  names:
    plural: externalsyncrules
    singular: externalsyncrule
    kind: ExternalSyncRule
    categories:
      - kube-external-sync
