apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-external-sync.fullname" . }}
  labels: {{- include "kube-external-sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-external-sync.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-external-sync.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
