apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-external-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-external-sync.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "kube-external-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "kube-external-sync.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-external-sync.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.deployment.env.LOG_LEVEL }}
            - name: LOG_FORMAT
              value: {{ .Values.deployment.env.LOG_FORMAT }}
            - name: LIVENESS_PORT
              value: '{{ .Values.deployment.port }}'
            - name: RESYNC_PERIOD
              value: {{ .Values.deployment.env.RESYNC_PERIOD }}
          ports:
            - name: health
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
