name: Pull Request Verification

on:
  pull_request:

# Kill the workflow if the PR is updated with a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-go:
    name: Pull Request Go Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Compile Executable
        run: go build cmd/kube-external-sync/main.go

      - name: Run unit tests
        run: go test ./... --cover

  pr-docker:
    name: Pull Request Docker Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t kube-external-sync .

  pr-generate:
    name: Pull Request Generate Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install controller-gen
        run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest

      - name: Generate DeepCopy file
        run: make generate

      - name: Check diffs
        run: |
          if [[ `git status --porcelain` ]]; then 
            echo "Changes" 
            exit 1
          else 
            echo "No Changes" 
          fi

  validate-helm-charts:
    name: Validate Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install helm
        uses: Azure/setup-helm@v3

      - name: Lint Helm Chart
        run: helm lint deploy/helm/kube-external-sync

      - name: Package Helm Chart
        run: helm package deploy/helm/kube-external-sync

      - name: Template Helm Chart
        run: helm template helm-charts deploy/helm/kube-external-sync
